# Generated by Django 3.2.7 on 2021-10-08 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositSerialID', models.CharField(blank=True, max_length=200, null=True)),
                ('customerName', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('depositDate', models.DateField(blank=True, null=True)),
                ('totalAmount', models.FloatField(default=0.0)),
                ('totalInterestPaid', models.FloatField(default=0.0)),
                ('clearanceDate', models.DateField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'B) Deposit List',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'A) Status List',
            },
        ),
        migrations.CreateModel(
            name='DepositItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(blank=True, max_length=300, null=True)),
                ('weight', models.FloatField(default=0.0)),
                ('itemRatePerTenGram', models.FloatField(default=0.0)),
                ('interestRate', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, null=True)),
                ('itemAmount', models.FloatField(default=0.0)),
                ('isWithdrawn', models.BooleanField(default=False)),
                ('withdrawalDate', models.DateField(blank=True, null=True)),
                ('interestPaid', models.FloatField(default=0.0)),
                ('isDeleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('depositID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.deposit')),
            ],
            options={
                'verbose_name_plural': 'B) Deposit Item List',
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='statusID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.status'),
        ),
    ]
