# Generated by Django 3.2.7 on 2021-10-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposititem',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
