# Generated by Django 3.2.7 on 2021-10-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_deposititem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposititem',
            name='month',
            field=models.FloatField(default=0.0),
        ),
    ]
