# Generated by Django 3.2.7 on 2021-10-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_deposititem_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='totalAmountPaid',
            field=models.FloatField(default=0.0),
        ),
    ]
