# Generated by Django 3.2.7 on 2021-10-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_deposit_totalamountpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='oldID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
