# Generated by Django 3.2.7 on 2021-10-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211028_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='totalCredit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='totalDebit',
            field=models.FloatField(default=0.0),
        ),
    ]
