# Generated by Django 3.2.7 on 2021-10-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211029_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='totalWeight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='totalWeightL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
