# Generated by Django 3.2.9 on 2021-12-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0008_auto_20211031_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposititem',
            name='chaning',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deposititem',
            name='san',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deposititem',
            name='tola',
            field=models.FloatField(default=0.0),
        ),
    ]
