# Generated by Django 3.2.9 on 2021-12-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0009_auto_20211203_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposititem',
            name='chaning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deposititem',
            name='san',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deposititem',
            name='tola',
            field=models.IntegerField(default=0),
        ),
    ]
