# Generated by Django 3.2.9 on 2021-12-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0010_auto_20211203_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='customerName',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='depositID',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='interest',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deposit',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
